# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class 4x < Formula
  desc "Multi-role AI development loop — Design, Code, Review, Test"
  homepage "https://github.com/ggwhite/4x"
  version "0.1.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ggwhite/4x/releases/download/v0.1.10/4x_0.1.10_darwin_amd64.tar.gz"
      sha256 "40feaf084567e9414562e24d81a25dff14382cd9355d96f2b1d09570ef94b1ed"

      define_method(:install) do
        bin.install "4x"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ggwhite/4x/releases/download/v0.1.10/4x_0.1.10_darwin_arm64.tar.gz"
      sha256 "04459a6883d5281f9a7bc8b7266ab7e3e2a6af6f54146135170be25122ef7773"

      define_method(:install) do
        bin.install "4x"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ggwhite/4x/releases/download/v0.1.10/4x_0.1.10_linux_amd64.tar.gz"
      sha256 "41940c634c09df570ef799b1dd4eb434e9efa0c4d591758621f7dc10768ef472"
      define_method(:install) do
        bin.install "4x"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ggwhite/4x/releases/download/v0.1.10/4x_0.1.10_linux_arm64.tar.gz"
      sha256 "7d9bbb91ab2f0ec3101af36994cffe008756935ef4a84c06b5f31f006dd17b42"
      define_method(:install) do
        bin.install "4x"
      end
    end
  end

  test do
    system "#{bin}/4x", "--version"
  end
end
