# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class 4x < Formula
  desc "Multi-role AI development loop — Design, Code, Review, Test"
  homepage "https://github.com/ggwhite/4x"
  version "0.1.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ggwhite/4x/releases/download/v0.1.9/4x_0.1.9_darwin_amd64.tar.gz"
      sha256 "0ea8d9fa540506ff6d2c1497894d8aac2ea2e010033692a9fed574e71ba4603d"

      define_method(:install) do
        bin.install "4x"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ggwhite/4x/releases/download/v0.1.9/4x_0.1.9_darwin_arm64.tar.gz"
      sha256 "db5c5a4d41e6692842f514a76424640b32713a0e926e559ba264673f716907ee"

      define_method(:install) do
        bin.install "4x"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ggwhite/4x/releases/download/v0.1.9/4x_0.1.9_linux_amd64.tar.gz"
      sha256 "55dfb364b02093f582bc4d1fa45dec676f596c2720ed1c57172fa7ba5c967b6f"
      define_method(:install) do
        bin.install "4x"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ggwhite/4x/releases/download/v0.1.9/4x_0.1.9_linux_arm64.tar.gz"
      sha256 "dc8e3a9e6d3dd2865d76f1df5b1c555e6150f3e96bc8963ec1141893ed1e176c"
      define_method(:install) do
        bin.install "4x"
      end
    end
  end

  test do
    system "#{bin}/4x", "--version"
  end
end
