# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fourx < Formula
  desc "Multi-role AI development loop — Design, Code, Review, Test"
  homepage "https://github.com/ggwhite/4x"
  version "0.3.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ggwhite/4x/releases/download/v0.3.8/4x_0.3.8_darwin_amd64.tar.gz"
      sha256 "a51a26e0393aab2a3fb2f39b9fa55fd8360cbff66d86e2170be1b5570a52a088"

      define_method(:install) do
        bin.install "4x"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ggwhite/4x/releases/download/v0.3.8/4x_0.3.8_darwin_arm64.tar.gz"
      sha256 "3741e73f8dd8445c476d85b0155f68339cf7c11dd77c406d7baf2620857a89c5"

      define_method(:install) do
        bin.install "4x"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ggwhite/4x/releases/download/v0.3.8/4x_0.3.8_linux_amd64.tar.gz"
      sha256 "d478690654284f1d4d093afca07102da450256a547355a01957aa7093fe21169"
      define_method(:install) do
        bin.install "4x"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ggwhite/4x/releases/download/v0.3.8/4x_0.3.8_linux_arm64.tar.gz"
      sha256 "db3edb6aa1660e160248cbb86a5af4c04dff61f92f44e46727eb41625ccffcbd"
      define_method(:install) do
        bin.install "4x"
      end
    end
  end

  test do
    system "#{bin}/4x", "--version"
  end
end
