# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fourx < Formula
  desc "Multi-role AI development loop — Design, Code, Review, Test"
  homepage "https://github.com/ggwhite/4x"
  version "0.3.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ggwhite/4x/releases/download/v0.3.6/4x_0.3.6_darwin_amd64.tar.gz"
      sha256 "a831680c57d8f71140931c9c953cc6e16be4a9fc28788ef49c564eb7bf4d4e5d"

      define_method(:install) do
        bin.install "4x"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ggwhite/4x/releases/download/v0.3.6/4x_0.3.6_darwin_arm64.tar.gz"
      sha256 "413a82e60147ae2b66bb3d95f740e3dd5f1edc153ae64ea3c0f1fa7b69496820"

      define_method(:install) do
        bin.install "4x"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ggwhite/4x/releases/download/v0.3.6/4x_0.3.6_linux_amd64.tar.gz"
      sha256 "c91624e03ea38bab9b6ee9bd2342c0f28650486c1ca24be4c1b5548568bced44"
      define_method(:install) do
        bin.install "4x"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ggwhite/4x/releases/download/v0.3.6/4x_0.3.6_linux_arm64.tar.gz"
      sha256 "695bcb7f5ae8858489acbd6fdb7c54a06d6af2c1096c5a821be2200eb01ba7c6"
      define_method(:install) do
        bin.install "4x"
      end
    end
  end

  test do
    system "#{bin}/4x", "--version"
  end
end
